trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: Login to aqua reg
  inputs:
    command: 'login'
    containerRegistry: 'aqua-reg'
- script: |
    mkdir $(Build.SourcesDirectory)/reports
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vsts/work/1/s:/code -v $(Build.SourcesDirectory)/reports:/reports registry.aquasec.com/scanner:6.5 scan --user $(USER) --password $(PASSWORD) --host $(HOST) --code-scan /code --jsonfile /reports/out.json --htmlfile /reports/out.html
  displayName: 'run scanner manually'
  continueOnError: true
- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(Build.SourcesDirectory)/reports/out.html'